language: php

php:
- 5.5.9

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer update

script:
  - vendor/bin/phpunit --configuration phpunit.xml
  - php tests/build/scripts/junit.php
  - . tests/build/bin/phpcs
  - . tests/build/bin/phpmd

notifications:
  on_success: always
  on_failure: always
